// pages/component/icon/index.js
Page({
  /**
   * 页面的初始数据
   */
  data: {
    iconList: [
      "arrow-right",
      "arrow-left",
      "arrow-down",
      "arrow-up",
      "password",
      "eye",
      "like",
      "search",
      "loading",
      "delete",
      "star",
      "phone",
      "user",
      "setting",
      "upload",
      "close",
      "uparrow",
      "downarrow",
      "leftarrow",
      "rightarrow",
      "round",
      "round-active",
      "square",
      "square-active",
      "star1-o",
      "star1",
      "like1",
      "like1-o",
      "error",
      "file",
      "add",
      "camera",
      "qrcode",
      "link",
      "wechat",
      "qq",
      "weibo",
      "gou",
      "pic",
      "success",
      "fail",
      "cart-o",
      "shop-o",
      "chat-o"
    ]
  }
});
